### ISSUE TITLE
Can this be used along with Laravel Cashier?

### ISSUE THREAD

**Issue by ghost** [oanhnn/laravel-pricing-plans#2]
Can this be used along with Laravel Cashier?

**Comment by oanhnn** [comment]
This package is designed for implement pricing plans and subscription system (like Laravel Cashier) but without payment. You can using this with Laravel Cashier (using Stripe). But i think Laravel Cashier with Stripe is very good. And my package will be useful if you wont use Laravel Cashier or you want make it with other payment provider (not Stripe).

**Comment by ghost** [comment]
@oanhnn I see thanks, I asked the question cause I Laravel Cashier doesn't provide plan features/subscription levels out of the box which would have been very helpful

**Comment by oanhnn** [comment]
@johnrobertsonsquid Laravel Cashier doesn't provide plan features/subscription levels because Stripe service was provided it.
https://stripe.com/docs/billing/subscriptions/products-and-plans

**Comment by oanhnn** [comment]
@johnrobertsonsquid Can you close this issue?
