### ISSUE TITLE
Create explicit examples or describe correctly

### ISSUE THREAD

**Issue by Bizarrus** [oanhnn/laravel-pricing-plans#6]
I've wondering, how i can use the package...

On the `Readme`, no explicit usage definitions are presented.

For **example**, when i wan't to create Plans: [Usage: Create features and plan](https://github.com/oanhnn/laravel-pricing-plans#create-features-and-plan)
How i must place the code? how i can create the plans/features?

**Comment by oanhnn** [comment]
I sorry about document.
You MUST create features and plans for you business service (product) to use the package.
The features and plans can make pricing table. 😄 
A subscription need reference to a plan.

**Comment by Bizarrus** [comment]
For others:

I had made it simple. I've created a `Seed` - Here i have created the packages/features.
